services:
  backend:
    build:
      context: ./backend
    container_name: oysirs-backend-dev
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env_file/dev.env
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    container_name: celery
    command: celery -A main worker -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - .env_file/dev.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./backend
    container_name: celery_beat
    command: celery -A main beat -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - .env_file/dev.env
    depends_on:
      - redis

