services:
  backend:
    build:
      context: ./backend
    container_name: backend-dev
    command: >
      sh -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

    env_file:
      - .env_file/dev.env

