# Generated by Django 5.0.3 on 2025-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_banktransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbvn',
            name='bvn',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='customeremail',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customermobile',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customername',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customernuban',
            name='nuban',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customerpassport',
            name='passport',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customertin',
            name='tin',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
