# Generated by Django 5.0.3 on 2025-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_customeraddress_unique_address_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbvn',
            name='bvn',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customermobile',
            name='mobile',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customernuban',
            name='nuban',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpassport',
            name='passport',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customertin',
            name='tin',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
